# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 3
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####
"""BlenderFDS, output formatting"""

from time import strftime, localtime
from sys import modules

import bpy

def format_comment(msgs):
    if isinstance(msgs,str): msgs = tuple((msgs,))
    return "".join(("! {}\n".format(msg) for msg in msgs or tuple()))

def format_body(values):
    return "".join(values or tuple())

def format_file_title():
    return format_comment((
        "Generated by BlenderFDS {}".format(".".join(str(x) for x in modules.get("blenderfds").bl_info["version"])),
        "Blender version: {}".format(bpy.app.version_string),
        "Blender file: {}".format(bpy.data.filepath),
        "Time: {}".format(strftime("%a, %d %b %Y %H:%M:%S", localtime())),
        ))

def format_section_title(name):
    return format_comment("=== {} ===".format(name))

def format_namelist_title(name):
    return format_comment("{}:".format(name))

# FIXME Move to bf_objects.py
def format_xb(value):
    return "XB={0[0]:.3f},{0[1]:.3f},{0[2]:.3f},{0[3]:.3f},{0[4]:.3f},{0[5]:.3f}".format(value)

def format_xyz(value):
    return "XYZ={0[0]:.3f},{0[1]:.3f},{0[2]:.3f}".format(value)

def format_pb(value):
    return "PB{0[0]}={0[1]:.3f}".format(value)
