# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 3
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####
"""BlenderFDS, output formatting"""

import bpy, time, sys

def format_comment(msgs):
    if isinstance(msgs,str): msgs = tuple((msgs,))
    return "".join(("! {}\n".format(msg) for msg in msgs or tuple()))

def format_body(values):
    return "".join(values or tuple())

def format_file_title():
    return format_comment((
        "Generated by BlenderFDS {}".format(".".join(str(x) for x in sys.modules.get("blenderfds").bl_info["version"])),
        "Blender version: {}".format(bpy.app.version_string),
        "Blender file: {}".format(bpy.data.filepath),
        "Time: {}".format(time.strftime("%a, %d %b %Y %H:%M:%S", time.localtime())),
        ))

def format_section_title(name):
    return format_comment("=== {} ===".format(name))

def format_namelist_title(name):
    return format_comment("{}:".format(name))
